### What is NumPy?

> NumPy is a Python library used for working with arrays
>
> It also has functions for working in domain of linear algebra, fourier transform, and matrices.

### Why Use NumPy?

> In Python we have lists that serve the purpose of arrays, but they are slow to process.
>
> NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.ts.

### Why is NumPy Faster Than Lists?

> NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.
>
> This behavior is called locality of reference in computer science.
>
> This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.ures.

In [1]:
# First program of numpy

import numpy as np # first we will import numpy ['np' used for shortcut]

arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


### Dimensions in Arrays

> * **0-D Arrays**
>
>> *0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.*
>
> * **1-D Arrays**
>
>> *An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.*
>>
>> We can also says that an array which have only one row called 1-D array*
>
> * **2-D Arrays**
>
>> *An array that has 1-D arrays as its elements is called a 2-D array.*
>>
>> *These are often used to represent matrix or 2nd order tensors.*
>
> * **3-D Arrays**
>
>> *An array that has 2-D arrays (matrices) as its elements is called 3-D array.*
>>
>> *These are often used to represent a 3rd order tensor.*

### Check Number of Dimensions

In [6]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


### Create Higher Dimensions Array

In [11]:
arr = np.array([1,2,3,4,5], ndmin=5)

print(arr)
print('Dimension of the array is:',arr.ndim,'-D')

[[[[[1 2 3 4 5]]]]]
Dimension of the array is: 5 -D


### Access Array Elements

> * Array indexing is the same as accessing an array element.
>
> * You can access an array element by referring to its index number.
>
> * The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc. etc.

In [12]:
arr = np.array([1, 2, 3, 4])

print(arr[1])

2


In [13]:
# Get third and fourth elements from the following array and add them.

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


# Access 2-D Arrays

> Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [2]:
# Access the element on the first row, second column:

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1]) # First value show the row, while 2nd value show the column

2nd element on 1st row:  2


In [17]:
# Access the element on the 2nd row, 5th column:

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


# Access 3-D Arrays

> To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element..

In [3]:
# Access the third element of the second array in the first array:

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


#### Explain Example

```python
arr[0, 1, 2] prints the value 6.

And this is why:

The first number represents the first dimension, which contains two arrays:
[[1, 2, 3], [4, 5, 6]]
and:
[[7, 8, 9], [10, 11, 12]]
Since we selected 0, we are left with the first array:
[[1, 2, 3], [4, 5, 6]]

The second number represents the second dimension, which also contains two arrays:
[1, 2, 3]
and:
[4, 5, 6]
Since we selected 1, we are left with the second array:
[4, 5, 6]

The third number represents the third dimension, which contains three values:
4
5
6
Since we selected 2, we end up with the third value:
6
```




#### Slicing Arrays

> Slicing in python means taking elements from one given index to another given index
>
> We pass slice instead of index like this: **[start:end]**
>
> We can also define the step, like this: **[start:end:step]**

In [4]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:])

[1 2 3 4 5 6 7]


In [7]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::1])

[1 2 3 4 5 6 7]


In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


#### Slicing 2D array

In [9]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [10]:
# From both elements, return index 2:

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [11]:
# From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


#### Checking the Data Type of an Array
* *The NumPy array object has a property called dtype that returns the data type of the array:*

In [12]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [13]:
arr = np.array([1.1, 2.3, 3.4, 4.2])

print(arr.dtype)

float64


#### Converting Data Type on Existing Arrays
> The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

In [15]:
arr = np.array([1.1, 2.1, 3.1])   # Float type data

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [16]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [17]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


#### NumPy Array Copy vs View

> ***The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.***
>
> **The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.**
>
> **The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.**

In [20]:
# Make a copy, change the original array, and display both arrays:

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()                    # Copy of the original Array
arr[0] = 42                       # changes made in the original Array

print(arr)
print(x)

# The copy SHOULD NOT be affected by the changes made to the original array.

[42  2  3  4  5]
[1 2 3 4 5]


In [22]:
# Make a view, change the original array, and display both arrays:

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()                    # View of the original Array
arr[0] = 42                       # changes made in the original Array
print(arr)
print(x)

# The view SHOULD be affected by the changes made to the original array.

[42  2  3  4  5]
[42  2  3  4  5]


In [25]:
# Make a view, change the view, and display both arrays:

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

# The original array SHOULD be affected by the changes made to the view.

[31  2  3  4  5]
[31  2  3  4  5]


#### Shape of an Array
> The shape of an array is the number of elements in each dimension.

In [4]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

# The example above returns (2, 4), which means that the array has 2 dimensions, where the first dimension has 2 elements and the second has 4.
# The example above returns (2, 4), which means that the array has 2 dimensions, where both array have 4 elements.

(2, 4)


In [5]:
arr = np.array([[[1, 2, 3, 4],[1, 2, 3, 4]], [[1, 2, 3, 4],[5, 6, 7, 8]]])

print(arr.shape)

(2, 2, 4)


In [6]:
arr = np.array([[[1, 2, 3, 4]]])

print(arr.shape)


(1, 1, 4)


In [14]:
arr = np.arange(30)
arr_reshape = arr.reshape((5,2, 3))
print(arr_reshape)
print(arr_reshape.shape)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]]]
(5, 2, 3)


#### Reshape From 1-D to 2-D

In [34]:
# Convert the following 1-D array with 12 elements into a 2-D array.

# The outermost dimension will have 4 arrays, each with 3 elements:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [35]:
# Convert the following 1-D array with 12 elements into a 3-D array.

# The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


#### Can We Reshape Into any Shape?

> * Yes, as long as the elements required for reshaping are equal in both shapes.
>
> * We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array
>
> * But we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

In [37]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 4)      
print(newarr)

[[1 2 3 4]
 [5 6 7 8]]


In [38]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3)    # 

print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,3)

#### Flattening the arrays

> Flattening array means converting a multidimensional array into a 1D array.
>
> We can use reshape(-1) to do this.

In [2]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


#### Iterating Arrays

> * Iterating means going through elements one by one.
>
> * As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.
>
> * If we iterate on a 1-D array it will go through each element one by one.

In [2]:
# Iterate on the elements of the following 1-D array:

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [4]:
# Iterate on each scalar element of the 2-D array:

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


> ***If we iterate on a n-D array it will go through n-1th dimension one by one.***

### Iterating 3-D Arrays
> * In a 3-D array it will go through all the 2-D arrays.

In [7]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


> * ***To return the actual values, the scalars, we have to iterate the arrays in each dimension.***

In [8]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


### Iterating Arrays Using nditer()

> * The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.

### Iterating on Each Scalar Element
> * In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

In [10]:
# Iterate through the following 3-D array:

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [44]:
# Iterate Specific Data

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr[0,1:]):
  print(x)

3
4


### Enumerated Iteration Using ndenumerate()

> * Enumeration means mentioning sequence number of somethings one by one.
>
> * Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.


In [47]:
# 1-D array

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [48]:
# 2D array

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [49]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(1, 0, 0) 5
(1, 0, 1) 6
(1, 1, 0) 7
(1, 1, 1) 8


### Joining Two Array

In [50]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [61]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2))

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [62]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


#### Joining Arrays Using Stack Functions

> * Stacking is same as concatenation, the only difference is that stacking is done along a new axis.
>
> * We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.
>
> * We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [68]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [77]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr3 = np.array([7, 8, 9])

arr = np.stack((arr1, arr2, arr3), axis=1)

print(arr)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [76]:
# Stacking along Rows

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr3 = np.array([7, 8, 9])

arr = np.hstack((arr1, arr2, arr3))

print(arr)

[1 2 3 4 5 6 7 8 9]


In [75]:
# Stacking along Columns

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr3 = np.array([7, 8, 9])

arr = np.vstack((arr1, arr2, arr3))

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [74]:
# Stacking Along Height (depth)

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr3 = np.array([7, 8, 9])

arr = np.dstack((arr1, arr2, arr3))

print(arr)

[[[1 4 7]
  [2 5 8]
  [3 6 9]]]


#### Searching Arrays

> ***You can search an array for a certain value, and return the indexes that get a match.***

>
> ***To search an array, use the where() method.***

In [78]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [81]:
# Find the indexes where the values are even:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [82]:
# Find the indexes where the values are odd:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6], dtype=int64),)


### The searchsorted() method is assumed to be used on sorted arrays.

In [84]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 9)

print(x)

3


In [85]:
# Find the indexes where the value 7 should be inserted, starting from the right:

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


### Sorting Arrays

> * Sorting means putting elements in an ordered sequence.
>
> * Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.
>
> * The NumPy ndarray object has a function called sort(), that will sort a specified array.

In [87]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))
print(arr)

[0 1 2 3]
[3 2 0 1]


> ***Note:*** *This method returns a copy of the array, leaving the original array unchanged.*

In [89]:
# Sort the array alphabetically:

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [90]:
# Sort a 2-D array:

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [ ]:
Filtering Arrays






#### Filtering Arrays

> Getting some elements out of an existing array and creating a new array out of them is called filtering.

> 
> In NumPy, you filter an array using a boolean index list.
>

> A boolean index list is a list of booleans corresponding to indexes in the array.

In [92]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [93]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [94]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


In [95]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [96]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True]
[42 44]


### Generate Random Numbers

In [105]:
from numpy import random # import random

x = random.randint(50)   # random int number

print(x)

49


In [108]:
x = random.rand()   # random float number but if we put value in it , it means that creat array of float numbers

print(x)

0.8749043924731553


In [101]:
x=random.randint(100, size=(5))    # random number array

print(x)

[62 99 65 52 76]


In [102]:
# Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:

x = random.randint(100, size=(3, 5))

print(x)

[[34 55 35 94  6]
 [ 1 37 53 47  8]
 [20 66 63 23 50]]


In [109]:
x = random.rand(5)

print(x)

[0.27254895 0.83103424 0.44407758 0.42812558 0.35666527]


In [110]:
# Generate a 2-D array with 3 rows, each row containing 5 random numbers:
x = random.rand(3, 5)

print(x)

[[0.23297446 0.33558643 0.06872536 0.70576433 0.5464089 ]
 [0.07700886 0.34026647 0.15657986 0.17527437 0.23754214]
 [0.41188225 0.18545187 0.69512956 0.61289877 0.42805313]]


In [113]:
# Return one of the values in an array:

x = random.choice([3, 5, 7, 9])

print(x)

7


In [115]:
x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[7 5 9 3 3]
 [9 5 5 9 7]
 [7 5 5 7 9]]
